### ISSUE TITLE
Chef Manage does not go through Chef Guard

### ISSUE THREAD

**Issue by Tech356** [schubergphilis/chef-guard#73] opened 2015-01-18 01:44 UTC
After upgrading to Chef 12, I was able to get Chef Guard working. I then installed opscode-manage and made a few changes through the WebUI. I noticed that these changes were not logged to the config repo by Chef Guard. 

Initial I configured the chef server like the Chef Guard instructions recommend. This works for the knife commands but not the WebUI.

```
lb['upstream'] = {
    "opscode-erchef"=>["127.0.0.2"],
}
```

Assuming opscode-manage was ignoring the `opscode-erchef` setting and talking directly to 127.0.0.1, I moved opscode_erchef to 127.0.0.2 and had Ghef Guard listen on 127.0.0.1.

```
# /etc/opscode/chef-server.rb
opscode_erchef['listen'] = "127.0.0.2"

# /opt/chef-guard/chef-guard.conf
[default]
  listen = 127.0.0.1
[chef]
  erchefip = 127.0.0.2
```

This had the same result as before, knife goes through Chef Guard but the WebUI does not. 

I looked into the configuration of opscode-manage, but did not see where to tell it to look for erchef. https://docs.chef.io/config_rb_manage.html

**Comment by svanharmelen** [comment] 2015-01-18 08:08
@Tech356 very nice, but your looking in the wrong direction... Your initial erchef setting are correct, so it's not in there.

I think this is due to the fact the urls have changed for Chef 12 so they are inline with the urls Enterprise Chef uses.

So what does the url to your nodes info webpage look like? I guess something like https://your.chef.server/organizations/name/nodes?

If so I think you have to configure Chef-Guard to for enterprise chef to make it work.

I'll make this done automatically in the next release comming up shortly...

**Comment by Tech356** [comment] 2015-01-19 15:31
@svanharmelen That was it. When I configured Chef-Guard for enterprise chef it started working. 

There is an outstanding issue related to the `default_orgname` chef sets up when upgrading. When I don't specify the organization in my knife.rb, the command succeeds using the default_orgname and does not get logged by Chef-Guard. Removing the `default_orgname` setting from `chef-server.rb` removes this unlogged path. If Chef-Guard can log those changes that would be good. If not, then a note should be added to the documentation to tell users to remove `default_orgname` so there isn't an unlogged path.

**Comment by svanharmelen** [comment] 2015-01-30 08:47
As you may have noticed I'm working my way through the open issues right now, and I wonder if you could provide me with a little more details about this one? For example do you have an example of the URL's your referring to?

I'll be on IRC today, so maybe hook up there to get this one clear (and fixed)...

**Comment by Tech356** [comment] 2015-08-11 20:31
When upgrading from Chef 11 OSS, the upgrade adds `default_orgname <org_name>` configuration setting. This allows the existing clients to continue talking to the server using the Chef 11 OSS style urls. Chef Guard will miss the Chef 11 OSS style calls when set to `type = enterprise`. 

From https://docs.chef.io/config_rb_server_optional_settings.html

```
The Chef server API used by the Open Source Chef server does not
have an /organizations/ORG_NAME endpoint. Use this setting to 
ensure that migrated Open Source Chef servers are able to 
connect to the Chef server API. This value should be the same 
as the name of the organization that was created during the 
upgrade from Open Source Chef version 11 to Chef server version
12, which means it will be identical to the ORG_NAME part of 
the /organizations endpoint in Chef server version 12. Default
value: the name of the organization specified during the upgrade 
process from Open Source Chef 11 to Chef server 12.
```

A workaround is to delete the `default_orgname <org_name>` setting so that only Chef 12 style urls are allowed. Although this means every node needs to have it's `chef_server_url` setting updated to the new Chef 12 style url.

**Comment by svanharmelen** [comment] 2015-08-11 21:19
@Tech356 thanks for the detailed info! I actually looked at this one earlier today and think I have a solution. But it will need some more testing so will cycle back when I confirmed the fix/change works.

**Comment by svanharmelen** [comment] 2018-12-27 12:04
Hi @Tech356! I'm going to close this issue as its very, very old. And even though it's still true, I don't think it's causing issues anywhere anymore. Thanks!

**Closed as completed by svanharmelen** 2018-12-27 12:04 UTC
Labels: enhancement
